version: "3.9"

services:
  auth-app:
    container_name: "authorization-BE"
    build: .
#    command: ./wait_psql.sh db ./auth-app
    command: ./auth-app
    restart: always
    networks:
      - migration
#    env_file:
#      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5436/postgres
      - DB_PASSWORD=postgres
    ports:
      - "8008:8008"
    depends_on:
      - auth-db
    volumes:
      - .:/app
  auth-db:
    image: postgres:15-alpine
    container_name: "auth-db"
    networks:
      migration:
        aliases:
          - database
#    env_file:
#      - .env
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d qtr_portal -U qtr_portal" ]
      interval: 5s
      retries: 5
    restart: always
  migrate:
    image: migrate/migrate
    networks:
      - migration
    volumes:
      - .:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@auth_db:5436/postgres?sslmode=disable", "up" ]
    links:
      - auth-db
    depends_on:
      - auth-db
  deployment-app:
    container_name: "deployment-service"
    build: .
    working_dir: /app
    command: uvicorn app.__main__:app --host 0.0.0.0 --port 8088 --reload
    ports:
      - "8088:8088"
    environment:
      - DOCKER_CLIENT_URL=unix://var/run/docker.sock
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  main-app:
    container_name: "main-api"
    build: .
    working_dir: /app
    command: bash -c 'alembic upgrade head && while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.__main__:app --host 0.0.0.0 --reload'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - main-db
    networks:
      - nginx_to_services
  main-db:
    image: postgres:15-alpine
    container_name: "postgres_db"
#    env_file:
#      - ./.env
    volumes:
      - postgres_main_api_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d qtr_portal -U qtr_portal" ]
      interval: 5s
      retries: 5
    restart: always
  frontend:
    container_name: "FE"
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - nginx_to_services
    expose:
      - "80"
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - "certificates:/etc/letsencrypt/"
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_to_services
    environment:
      - ENV=development
      - APPLICATION_URL=http://rzhakalol

networks:
  migration:
  nginx_to_services:

volumes:
  postgres_auth_data:
  postgres_deployment_data:
  postgres_main_api_data:
  certificates:
